#pragma once

#include <CoreMedia/CoreMedia.h>


Float64 CMAudioFormatDescriptionGetFLVFrameRate(CMAudioFormatDescriptionRef audioFormatDescription);

Float64 CMAudioFormatDescriptionGetFLVDataRate(CMAudioFormatDescriptionRef audioFormatDescription);

uint32_t CMAudioFormatDescriptionGetFLVCodec(CMAudioFormatDescriptionRef audioFormatDescription);
