#pragma once

#include <CoreMedia/CoreMedia.h>

uint8_t CMFormatDescriptionGetFLVAudioHeader(CMFormatDescriptionRef formatDescription);
CFDataRef CMFormatDescriptionCopyFLVAudioPrefixData(CMFormatDescriptionRef formatDescription);

CFDataRef CMFormatDescriptionCopyFLVAudioStartData(CMFormatDescriptionRef formatDescription);
CFDataRef CMFormatDescriptionCopyFLVAudioFinishData(CMFormatDescriptionRef formatDescription);

uint8_t CMFormatDescriptionGetFLVVideoHeader(CMFormatDescriptionRef formatDescription, Boolean isKeyframe);
CFDataRef CMFormatDescriptionCopyFLVVideoPrefixData(CMFormatDescriptionRef formatDescription, Boolean isKeyframe);

Boolean CMFormatDescriptionHasFLVVideoStartData(CMFormatDescriptionRef formatDescription);
CFDataRef CMFormatDescriptionCopyFLVVideoStartData(CMFormatDescriptionRef formatDescription);

Boolean CMFormatDescriptionHasFLVVideoFinishData(CMFormatDescriptionRef formatDescription);
CFDataRef CMFormatDescriptionCopyFLVVideoFinishData(CMFormatDescriptionRef formatDescription);

